# -*- coding: utf-8 -*-
"""constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yrydbh6LrFTDIaP5fJBG_Qd_Zs6_RQMh
"""

#image size of the cropped face
IMG_SHAPE = (160, 160)
#contains file location of the video file
VIDEO_FILE="meet.mp4"
#contains all the images obtained from frame
IMAGE_FOLDER="/images"
MODEL_PATH="model2.json"
WEIGHT_PATH="model2.h5"
FACENET_MODEL_PATH="facenet_keras.h5"
DATA_PATH="db.csv"