# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AueSd-XBaHhsAvNSn8H9TPdUzMp_xtPv
"""

"""
This code explains the how to use face recognition pipeline.
Snippets from this file will be used in production.
"""

"""
main.py must have minimal imports. Try to cover all the imports in calling modules.
"""
from FaceRecognition.face_recognition import FaceDetection, FaceRecognition, FaceVerification  # noqa
from FaceRecognition.utils import FaceRecognitionUtils
import os

fd=FaceDetection()
fv=FaceVerification()
fr=FaceRecognition()
fu=FaceRecognitionUtils()

#--------------------------------------
#image size of the cropped face
IMG_SHAPE = (160, 160)
#contains file location of the video file
VIDEO_FILE="/content/drive/My Drive/git/meet1.mp4"
#contains all the images obtained from frame
IMAGE_FOLDER="/content/drive/My Drive/git/images/"
MODEL_PATH="/content/drive/My Drive/git/model2.json"
WEIGHT_PATH="/content/drive/My Drive/git/model2v2.h5"
FACENET_MODEL_PATH="/content/model/facenet_keras.h5"
DATA_PATH="db.csv"
#--------------------------------------

#filename comming from raspberry pi cam when a face is detected.
input_video=VIDEO_FILE
fu.video_to_frame(input_video,IMAGE_FOLDER)
#scandir is supported on python versions abpve 3.5

with os.scandir("/content/drive/My Drive/git/images") as it:
    for entry in it:
        if entry.name.endswith(".jpg"):
            path="/content/drive/My Drive/git/images"+entry.name
            face=fd.find_face(path)
            model=fv.get_facenet_model(FACENET_MODEL_PATH)
            embeddings=fv.get_embedding(model,face)
            data,labels=fr.load_database(DATA_PATH) # CHECK HERE NEED TO UPDATE
            identified=check_in_db(data,embedding,labels)
            print(identified)
            #if identified != None:
            #    print(identified) #TEXT CONVERSION HERE
            #else:
            #    print("Add the person?") #IF YES, THEN RUN THE FUNCTION
            #    print("name?")#ADD NAME OF THE PERSON
            #    add_in_db(person_name,embeddings)

"""
Code on how to use face recognition.
"""

